mode = "dark"

accent = "#F0B87E"
selection = "#233B52"
muted = "#667B92"

background = "#121B26"
dark_background = "#0A1119"
darker_background = "#060A0F"
lighter_background = "#1F2E3D"

foreground = "#D6DEE8"
dark_foreground = "#8092A6"
light_foreground = "#E4EAF2"
bright_foreground = "#F3F7FC"

hyprland_active_border = "rgba(f0b87eee) rgba(5c89c2ee)"
hyprland_inactive_border = "rgba(2a3b4faa)"

red = "#DC6A62"
yellow = "#F2C879"
orange = "#EE9858"
green = "#A4D497"
cyan = "#6FB4C7"
blue = "#5C89C2"
magenta = "#A587A8"
brown = "#A27E61"

bright_red = "#EF9089"
bright_yellow = "#F7DB9C"
bright_green = "#C4EDB6"
bright_cyan = "#8ECBDB"
bright_blue = "#7FA3D6"
bright_magenta = "#BC9FBE"
